Update __init__.py
Still had an error:
TypeError: load_platform() missing 1 required positional argument: 'hass_config'

Added 'hass' as first argument for load_platform() to fix the problem for me.
Got the idea from this post: https://community.home-assistant.io/t/integrate-with-opensprinkler/18142/63